{% set name = "http-ece" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/http_ece-{{ version }}.tar.gz
  sha256: b5920f8efb8e1b5fb025713e3b36fda54336262010634b26dc1f98f85d1eb3de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cryptography >=2.5

test:
  imports:
    - http_ece
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martinthomson/encrypted-content-encoding
  summary: Encrypted Content Encoding for HTTP
  license: MIT
  license_file:
    - LICENSE
    - LICENSE

extra:
  recipe-maintainers:
    - jsta
