{% set name = "http-ece" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/http_ece-{{ version }}.tar.gz
  sha256: 8c6ab23116bbf6affda894acfd5f2ca0fb8facbcbb72121c11c75c33e7ce8cff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=2.5

test:
  imports:
    - http_ece
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/martinthomson/encrypted-content-encoding
  summary: Encrypted Content Encoding for HTTP
  license: MIT
  license_file:
    - LICENSE
    - LICENSE

extra:
  recipe-maintainers:
    - jsta
